//! Foreground model resolution.
//!
//! This module is the seam between a foreground turn and the application's
//! provider configuration.  It owns the order in which non-secret config,
//! keychain credentials, thinking settings, and the provider are resolved.
//! Callers receive a ready provider plus a non-secret identity; credentials
//! never cross this seam.

use crate::keychain::ApiCredentials;
use crate::llm::{
    create_provider_for_app, resolve_thinking_settings, LlmProvider, ModelAuthMode, ProviderConfig,
    ThinkingSettings,
};
use crate::AppState;
use rusqlite::{params, Connection, OptionalExtension};
use std::sync::{Arc, Mutex};
use tauri::AppHandle;

/// Inputs that affect one foreground model resolution.
#[derive(Debug, Clone, Copy)]
pub(crate) struct ForegroundModelRequest<'a> {
    pub session_id: &'a str,
    pub requested_thinking_effort: Option<&'a str>,
    pub now: i64,
}

/// Stable, non-secret model identity used by the foreground run and by the
/// internal delegation tool's durable binding.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ForegroundModelIdentity {
    pub provider: String,
    pub model: String,
    pub provider_profile_ref: String,
    pub credential_handle_ref: String,
}

/// The result required by the foreground runner.  API credentials are kept
/// inside the provider implementation and are intentionally not returned as
/// fields or serialized values.
pub(crate) struct ResolvedForegroundModel {
    pub provider: Box<dyn LlmProvider>,
    pub thinking_settings: Option<ThinkingSettings>,
    pub identity: ForegroundModelIdentity,
}

/// Deterministic offline provider used only by the compiled desktop E2E app.
/// Keeping this behind a Cargo feature prevents test behavior from being
/// enabled by an environment variable in production builds.
#[cfg(feature = "desktop-e2e")]
#[derive(serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
enum DesktopE2eReply {
    Text {
        text: String,
        #[serde(default, rename = "expectUserContentIncludes")]
        expect_user_content_includes: Vec<String>,
        #[serde(default, rename = "forbiddenToolNames")]
        forbidden_tool_names: Vec<String>,
    },
    ToolCalls {
        calls: Vec<crate::llm::ToolCall>,
        #[serde(default)]
        text: Option<String>,
    },
    /// Resolve the exact delivery identifier from the trusted structured
    /// context injected by the foreground assembler.  A static E2E fixture
    /// cannot know the durable identifier generated by the real delegation
    /// path, so it must never carry one in its script.
    DeliveryReview {
        decision: DesktopE2eDeliveryDecision,
        #[serde(default)]
        text: Option<String>,
    },
}

/// The only Main-Agent outcomes accepted by the desktop E2E review fixture.
/// Deserialization rejects any other value before the fake provider can
/// construct a tool call.
#[cfg(feature = "desktop-e2e")]
#[derive(serde::Deserialize, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum DesktopE2eDeliveryDecision {
    Accept,
    NeedsDecision,
}

#[cfg(feature = "desktop-e2e")]
impl DesktopE2eDeliveryDecision {
    fn as_str(self) -> &'static str {
        match self {
            Self::Accept => "accept",
            Self::NeedsDecision => "needs_decision",
        }
    }
}

#[cfg(feature = "desktop-e2e")]
struct DesktopE2eProvider {
    replies: Vec<DesktopE2eReply>,
}

// Model resolution happens once per foreground turn. Keep the deterministic
// desktop script cursor at process scope so one E2E scenario can exercise
// several user turns without replaying the first scripted response each time.
#[cfg(feature = "desktop-e2e")]
static DESKTOP_E2E_NEXT_REPLY: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(0);

#[cfg(feature = "desktop-e2e")]
#[async_trait::async_trait]
impl LlmProvider for DesktopE2eProvider {
    fn name(&self) -> &str {
        "desktop-e2e"
    }

    async fn chat(
        &self,
        messages: &[crate::llm::Message],
        tools: Option<&[crate::llm::ToolSchema]>,
        _thinking: Option<&ThinkingSettings>,
    ) -> Result<crate::llm::LlmResponse, String> {
        // A reviewed delivery is an asynchronous system follow-up, so it must
        // not compete with unrelated interactive turns for a global scripted
        // reply cursor. Its one-tool surface is also an unambiguous E2E-only
        // protocol boundary.
        if desktop_e2e_is_reviewed_delivery_summary(tools) {
            if desktop_e2e_has_review_result(messages) {
                return Ok(crate::llm::LlmResponse::Text {
                    text: "资料检索已完成：AngelBot E2E documentation 提供了可核验的公开测试资料；证据来自 docs.example.test，未发现需要你处理的不确定项。".to_string(),
                    stop_reason: crate::llm::StopReason::EndTurn,
                });
            }
            return desktop_e2e_delivery_review_response(
                DesktopE2eDeliveryDecision::Accept,
                Some("我会确认这份已审校的资料，并整理成面向你的结论。".to_string()),
                messages,
                tools,
            );
        }
        let index = DESKTOP_E2E_NEXT_REPLY.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        match self.replies.get(index) {
            Some(DesktopE2eReply::Text {
                text,
                expect_user_content_includes,
                forbidden_tool_names,
            }) => {
                desktop_e2e_assert_request(
                    messages,
                    tools,
                    expect_user_content_includes,
                    forbidden_tool_names,
                )?;
                Ok(crate::llm::LlmResponse::Text {
                    text: text.clone(),
                    stop_reason: crate::llm::StopReason::EndTurn,
                })
            }
            Some(DesktopE2eReply::ToolCalls { calls, text }) => {
                Ok(crate::llm::LlmResponse::ToolCalls {
                    calls: calls.clone(),
                    text: text.clone(),
                    stop_reason: crate::llm::StopReason::ToolUse,
                })
            }
            Some(DesktopE2eReply::DeliveryReview { decision, text }) => {
                desktop_e2e_delivery_review_response(*decision, text.clone(), messages, tools)
            }
            None => Err(format!(
                "desktop E2E model script exhausted after {index} replies"
            )),
        }
    }
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_assert_request(
    messages: &[crate::llm::Message],
    tools: Option<&[crate::llm::ToolSchema]>,
    expected: &[String],
    forbidden: &[String],
) -> Result<(), String> {
    let user_content = messages
        .iter()
        .filter(|message| message.role == "user")
        .map(|message| message.content.as_str())
        .collect::<Vec<_>>()
        .join("\n");
    if expected.iter().any(|marker| !user_content.contains(marker)) {
        return Err("desktop E2E user-data assertion failed".to_string());
    }
    if tools.is_some_and(|schemas| {
        schemas
            .iter()
            .any(|schema| forbidden.contains(&schema.name))
    }) {
        return Err("desktop E2E capability assertion failed".to_string());
    }
    Ok(())
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_is_reviewed_delivery_summary(tools: Option<&[crate::llm::ToolSchema]>) -> bool {
    matches!(tools, Some([schema]) if schema.name == "review_delegated_delivery")
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_has_review_result(messages: &[crate::llm::Message]) -> bool {
    messages.iter().any(|message| {
        message.role == "tool"
            && message.tool_call_id.as_deref() == Some("desktop-e2e-review-delegated-delivery")
    })
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_delivery_review_response(
    decision: DesktopE2eDeliveryDecision,
    text: Option<String>,
    messages: &[crate::llm::Message],
    tools: Option<&[crate::llm::ToolSchema]>,
) -> Result<crate::llm::LlmResponse, String> {
    if !tools.is_some_and(|schemas| {
        schemas
            .iter()
            .any(|schema| schema.name == "review_delegated_delivery")
    }) {
        return Err(
            "desktop E2E delivery review requires the review_delegated_delivery tool".to_string(),
        );
    }

    let delivery_id = desktop_e2e_unique_delivery_id(messages)?;
    Ok(crate::llm::LlmResponse::ToolCalls {
        calls: vec![crate::llm::ToolCall {
            id: "desktop-e2e-review-delegated-delivery".to_string(),
            name: "review_delegated_delivery".to_string(),
            arguments: serde_json::json!({
                "delivery_id": delivery_id,
                "decision": decision.as_str(),
            }),
        }],
        text,
        stop_reason: crate::llm::StopReason::ToolUse,
    })
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_unique_delivery_id(messages: &[crate::llm::Message]) -> Result<String, String> {
    const OPEN: &str = "<delegated_deliveries>";
    const CLOSE: &str = "</delegated_deliveries>";

    let mut delivery_ids = Vec::new();
    for message in messages.iter().filter(|message| message.role == "system") {
        let mut remaining = message.content.as_str();
        while let Some(open_offset) = remaining.find(OPEN) {
            if remaining[..open_offset].contains(CLOSE) {
                return Err("desktop E2E delegated-delivery context is malformed".to_string());
            }
            let after_open = &remaining[open_offset + OPEN.len()..];
            let close_offset = after_open
                .find(CLOSE)
                .ok_or_else(|| "desktop E2E delegated-delivery context is malformed".to_string())?;
            let payload = &after_open[..close_offset];
            let mut parsed_any = false;
            for value in
                serde_json::Deserializer::from_str(payload).into_iter::<serde_json::Value>()
            {
                parsed_any = true;
                let value = value.map_err(|_| {
                    "desktop E2E delegated-delivery context is malformed".to_string()
                })?;
                let delivery_id = value
                    .get("delivery_id")
                    .and_then(serde_json::Value::as_str)
                    .filter(|value| desktop_e2e_valid_delivery_id(value))
                    .ok_or_else(|| {
                        "desktop E2E delegated-delivery context has an invalid delivery_id"
                            .to_string()
                    })?;
                delivery_ids.push(delivery_id.to_string());
            }
            if !parsed_any {
                return Err("desktop E2E delegated-delivery context is empty".to_string());
            }
            remaining = &after_open[close_offset + CLOSE.len()..];
        }
        if remaining.contains(CLOSE) {
            return Err("desktop E2E delegated-delivery context is malformed".to_string());
        }
    }

    match delivery_ids.as_slice() {
        [delivery_id] => Ok(delivery_id.clone()),
        [] => {
            Err("desktop E2E delivery review requires exactly one structured delivery".to_string())
        }
        _ => {
            Err("desktop E2E delivery review requires exactly one structured delivery".to_string())
        }
    }
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_valid_delivery_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

/// Stable error categories exposed by the model-resolution seam.  The raw
/// provider/keychain error is deliberately not retained: it can contain an
/// endpoint, environment detail, or credential material unsuitable for UI or
/// model context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ModelResolutionError {
    InvalidConfiguration,
    MissingCredentials,
    CredentialStoreUnavailable,
    InvalidThinkingSettings,
    ProviderUnavailable,
    SessionBindingFailed,
}

impl std::fmt::Display for ModelResolutionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let message = match self {
            Self::InvalidConfiguration => "LLM provider configuration is invalid",
            Self::MissingCredentials => "LLM provider credentials are not configured",
            Self::CredentialStoreUnavailable => "LLM provider credentials are unavailable",
            Self::InvalidThinkingSettings => "LLM reasoning settings are invalid",
            Self::ProviderUnavailable => "LLM provider could not be initialized",
            Self::SessionBindingFailed => "LLM provider could not be bound to this session",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for ModelResolutionError {}

/// Deep module for foreground provider resolution.  It does not create
/// delegations, schedule workers, or expose foreground conversation context.
pub(crate) struct ForegroundModelFactory<'a> {
    app: Option<&'a AppHandle>,
    db: Arc<Mutex<Connection>>,
}

impl<'a> ForegroundModelFactory<'a> {
    pub(crate) fn new(app: Option<&'a AppHandle>, state: &AppState) -> Self {
        Self {
            app,
            db: state.db.clone(),
        }
    }

    pub(crate) fn resolve(
        &self,
        request: ForegroundModelRequest<'_>,
    ) -> Result<ResolvedForegroundModel, ModelResolutionError> {
        #[cfg(feature = "desktop-e2e")]
        if let Some(replies) = desktop_e2e_replies()? {
            let config = ProviderConfig {
                protocol: None,
                auth_mode: crate::llm::ModelAuthMode::ApiKey,
                credential_ref: None,
                provider: "desktop-e2e".to_owned(),
                model: "deterministic".to_owned(),
                base_url: "offline://desktop-e2e".to_owned(),
                api_key: String::new(),
                max_tokens: 1_024,
                temperature: 0.0,
            };
            bind_session_provider(&self.db, request.session_id, &config, request.now)?;
            return Ok(ResolvedForegroundModel {
                provider: Box::new(DesktopE2eProvider { replies }),
                thinking_settings: None,
                identity: ForegroundModelIdentity {
                    provider_profile_ref: config.profile_identity(),
                    credential_handle_ref: config.credential_identity(),
                    provider: config.provider,
                    model: config.model,
                },
            });
        }

        let config = self.resolve_config()?;
        validate_provider_identity(&config)?;

        // Preserve the existing foreground ordering: bind the resolved model
        // before constructing the provider, so a settings change is reflected
        // in the session even when provider initialization fails afterwards.
        bind_session_provider(&self.db, request.session_id, &config, request.now)?;

        let thinking_settings =
            resolve_thinking_settings(&config, request.requested_thinking_effort)
                .map_err(|_| ModelResolutionError::InvalidThinkingSettings)?;

        let provider = create_provider_for_app(&config, self.app)
            .map_err(|_| classify_provider_configuration(&config))?;

        Ok(ResolvedForegroundModel {
            provider,
            thinking_settings,
            identity: ForegroundModelIdentity {
                provider_profile_ref: config.profile_identity(),
                credential_handle_ref: config.credential_identity(),
                provider: config.provider,
                model: config.model,
            },
        })
    }

    fn resolve_config(&self) -> Result<ProviderConfig, ModelResolutionError> {
        resolve_model_config(self.app)
    }
}

pub(crate) fn resolve_model_config(
    app: Option<&AppHandle>,
) -> Result<ProviderConfig, ModelResolutionError> {
    crate::commands::api_config::load_config_from_file_checked()
        .map_err(|_| ModelResolutionError::InvalidConfiguration)?;
    let file_config = crate::commands::api_config::load_api_config_internal();
    let credentials = if file_config
        .as_ref()
        .is_some_and(|config| config.auth_mode != ModelAuthMode::ApiKey)
    {
        Ok(None)
    } else {
        read_credentials_safely(app)
    };
    resolve_config_from_sources(file_config, credentials)
}

#[cfg(feature = "desktop-e2e")]
fn desktop_e2e_replies() -> Result<Option<Vec<DesktopE2eReply>>, ModelResolutionError> {
    if let Ok(script) = std::env::var("ANGELBOT_DESKTOP_E2E_MODEL_SCRIPT") {
        let replies: Vec<DesktopE2eReply> = serde_json::from_str(&script)
            .map_err(|_| ModelResolutionError::InvalidConfiguration)?;
        if replies.is_empty() {
            return Err(ModelResolutionError::InvalidConfiguration);
        }
        return Ok(Some(replies));
    }
    Ok(std::env::var("ANGELBOT_DESKTOP_E2E_MODEL_RESPONSE")
        .ok()
        .map(|text| {
            vec![DesktopE2eReply::Text {
                text,
                expect_user_content_includes: Vec::new(),
                forbidden_tool_names: Vec::new(),
            }]
        }))
}

/// Resolve the same source precedence used by the previous message command.
/// This pure helper is also the test seam for configuration and keychain
/// fallback without constructing a Tauri AppHandle.
pub(crate) fn resolve_config_from_sources(
    file_config: Option<ProviderConfig>,
    credentials: Result<Option<ApiCredentials>, ()>,
) -> Result<ProviderConfig, ModelResolutionError> {
    if let Some(mut config) = file_config {
        if config.auth_mode == ModelAuthMode::ApiKey && config.api_key.is_empty() {
            if let Ok(Some(creds)) = credentials {
                if !creds.api_key.is_empty()
                    && (config.provider.is_empty()
                        || creds.provider.is_empty()
                        || creds.provider == config.provider)
                {
                    config.api_key = creds.api_key;
                    if config.provider.is_empty() {
                        config.provider = creds.provider;
                    }
                    if config.model.is_empty() {
                        config.model = creds.model;
                    }
                }
            }
        }
        return Ok(config);
    }

    match credentials {
        Ok(Some(creds)) if creds.is_valid() => Ok(ProviderConfig {
            protocol: None,
            auth_mode: crate::llm::ModelAuthMode::ApiKey,
            credential_ref: None,
            provider: creds.provider.clone(),
            model: creds.model.clone(),
            base_url: crate::llm::get_default_base_url(&creds.provider),
            api_key: creds.api_key,
            max_tokens: 4096,
            temperature: 0.7,
        }),
        Ok(Some(_)) => Err(ModelResolutionError::MissingCredentials),
        Ok(None) => Err(ModelResolutionError::MissingCredentials),
        Err(()) => Err(ModelResolutionError::CredentialStoreUnavailable),
    }
}

fn read_credentials_safely(app: Option<&AppHandle>) -> Result<Option<ApiCredentials>, ()> {
    let Some(app) = app else {
        return Ok(None);
    };
    match crate::keychain::read_credentials(app) {
        Ok(credentials) if !credentials.api_key.is_empty() => Ok(Some(credentials)),
        Ok(_) => Ok(None),
        Err(_) => Err(()),
    }
}

fn validate_provider_identity(config: &ProviderConfig) -> Result<(), ModelResolutionError> {
    if config.provider.trim().is_empty() || config.model.trim().is_empty() {
        return Err(ModelResolutionError::InvalidConfiguration);
    }
    Ok(())
}

fn classify_provider_configuration(config: &ProviderConfig) -> ModelResolutionError {
    if config.requires_api_key() && config.api_key.trim().is_empty() {
        ModelResolutionError::MissingCredentials
    } else {
        ModelResolutionError::ProviderUnavailable
    }
}

fn bind_session_provider(
    db: &Arc<Mutex<Connection>>,
    session_id: &str,
    config: &ProviderConfig,
    now: i64,
) -> Result<(), ModelResolutionError> {
    let conn = db
        .lock()
        .map_err(|_| ModelResolutionError::SessionBindingFailed)?;
    bind_session_provider_in_conn(&conn, session_id, config, now)
}

pub(crate) fn bind_session_provider_in_conn(
    conn: &Connection,
    session_id: &str,
    config: &ProviderConfig,
    now: i64,
) -> Result<(), ModelResolutionError> {
    validate_provider_identity(config)?;
    let existing: Option<String> = conn
        .query_row(
            "SELECT metadata FROM sessions WHERE id=?1",
            [session_id],
            |row| row.get(0),
        )
        .optional()
        .map_err(|_| ModelResolutionError::SessionBindingFailed)?
        .flatten();
    let mut metadata = existing
        .as_deref()
        .and_then(|value| serde_json::from_str::<serde_json::Value>(value).ok())
        .filter(|value| value.is_object())
        .unwrap_or_else(|| match existing {
            Some(value) => serde_json::json!({"legacyMetadata":value}),
            None => serde_json::json!({}),
        });
    metadata["modelConnectionBinding"] = serde_json::json!({
        "version":1, "profileRef":config.profile_identity(), "credentialRef":config.credential_identity(),
        "modelRef":format!("model:{}",config.model),
    });
    conn.execute(
        "UPDATE sessions SET agent_provider = ?1, agent_model = ?2, updated_at = ?3, metadata=?5 WHERE id = ?4",
        params![config.provider, config.model, now, session_id, metadata.to_string()],
    )
    .map_err(|_| ModelResolutionError::SessionBindingFailed)?;
    Ok(())
}

pub(crate) fn session_model_binding(
    conn: &Connection,
    session_id: &str,
    provider: &str,
    model: &str,
) -> Result<crate::agent::delegated_model_binding::DelegatedModelBindingRequest, String> {
    let metadata: Option<String> = conn
        .query_row(
            "SELECT metadata FROM sessions WHERE id=?1",
            [session_id],
            |row| row.get(0),
        )
        .map_err(|_| "the delegation model binding is unavailable")?;
    let value = metadata
        .as_deref()
        .and_then(|metadata| serde_json::from_str::<serde_json::Value>(metadata).ok());
    let (profile, credential) = if let Some(binding) = value
        .as_ref()
        .and_then(|value| value.get("modelConnectionBinding"))
    {
        if binding["version"] != 1 || binding["modelRef"] != format!("model:{model}") {
            return Err("the delegation model binding is invalid".into());
        }
        (
            binding["profileRef"]
                .as_str()
                .ok_or("missing model profile")?
                .to_string(),
            binding["credentialRef"]
                .as_str()
                .ok_or("missing credential reference")?
                .to_string(),
        )
    } else {
        (format!("provider:{provider}"), "keychain:default".into())
    };
    crate::agent::delegated_model_binding::DelegatedModelBindingRequest::new(
        profile,
        format!("model:{model}"),
        credential,
        1,
    )
    .map_err(|_| "the delegation model binding is invalid".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::migrate;

    #[test]
    fn confirmation_rebuild_uses_durable_connection_without_runtime_configuration() {
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();
        conn.execute("INSERT INTO sessions(id,title,created_at,updated_at,metadata) VALUES('binding','fixture',1,1,'{\"preserved\":true}')", []).unwrap();
        let config = ProviderConfig {
            provider: "openai".into(),
            model: "fixture".into(),
            protocol: Some(crate::llm::ModelProtocol::OpenaiResponses),
            auth_mode: ModelAuthMode::ChatgptPlan,
            base_url: "https://api.openai.com/v1".into(),
            credential_ref: Some(format!("chatgpt_plan_v1_{}", uuid::Uuid::new_v4())),
            api_key: "must-not-persist".into(),
            ..ProviderConfig::default()
        };
        bind_session_provider_in_conn(&conn, "binding", &config, 2).unwrap();
        let binding = session_model_binding(&conn, "binding", "openai", "fixture").unwrap();
        assert_eq!(binding.provider_profile_ref, config.profile_identity());
        assert_eq!(binding.credential_handle_ref, config.credential_identity());
        let metadata: String = conn
            .query_row(
                "SELECT metadata FROM sessions WHERE id='binding'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert!(!metadata.contains("must-not-persist"));
        assert!(serde_json::from_str::<serde_json::Value>(&metadata).unwrap()["preserved"] == true);
        assert!(session_model_binding(&conn, "binding", "openai", "changed-model").is_err());
    }

    fn config(provider: &str, model: &str, api_key: &str) -> ProviderConfig {
        ProviderConfig {
            provider: provider.to_string(),
            model: model.to_string(),
            api_key: api_key.to_string(),
            ..ProviderConfig::default()
        }
    }

    #[test]
    fn configured_provider_wins_and_keychain_fills_empty_fields() {
        let from_file = config("", "", "");
        let credentials = ApiCredentials {
            provider: "anthropic".into(),
            model: "claude-test".into(),
            api_key: "secret-key".into(),
        };
        let resolved = resolve_config_from_sources(Some(from_file), Ok(Some(credentials))).unwrap();
        assert_eq!(resolved.provider, "anthropic");
        assert_eq!(resolved.model, "claude-test");
        assert_eq!(resolved.api_key, "secret-key");
    }

    #[test]
    fn explicit_config_identity_and_key_are_preserved_over_keychain() {
        let from_file = config("deepseek", "deepseek-v4-pro", "file-key");
        let credentials = ApiCredentials {
            provider: "anthropic".into(),
            model: "claude-test".into(),
            api_key: "keychain-key".into(),
        };
        let resolved = resolve_config_from_sources(Some(from_file), Ok(Some(credentials))).unwrap();
        assert_eq!(resolved.provider, "deepseek");
        assert_eq!(resolved.model, "deepseek-v4-pro");
        assert_eq!(resolved.api_key, "file-key");
    }

    #[test]
    fn credentials_never_cross_provider_identity() {
        let from_file = config("deepseek", "deepseek-v4-pro", "");
        let credentials = ApiCredentials {
            provider: "anthropic".into(),
            model: "claude-test".into(),
            api_key: "anthropic-key".into(),
        };
        let resolved = resolve_config_from_sources(Some(from_file), Ok(Some(credentials))).unwrap();
        assert_eq!(resolved.provider, "deepseek");
        assert!(resolved.api_key.is_empty());
    }

    #[test]
    fn missing_or_unreadable_credentials_fail_closed() {
        assert_eq!(
            resolve_config_from_sources(None, Ok(None)).unwrap_err(),
            ModelResolutionError::MissingCredentials
        );
        assert_eq!(
            resolve_config_from_sources(None, Err(())).unwrap_err(),
            ModelResolutionError::CredentialStoreUnavailable
        );
        let invalid = ApiCredentials {
            provider: "anthropic".into(),
            model: "claude-test".into(),
            api_key: String::new(),
        };
        assert_eq!(
            resolve_config_from_sources(None, Ok(Some(invalid))).unwrap_err(),
            ModelResolutionError::MissingCredentials
        );
    }

    #[test]
    fn invalid_config_and_session_binding_errors_are_typed() {
        assert_eq!(
            validate_provider_identity(&config("", "model", "key")).unwrap_err(),
            ModelResolutionError::InvalidConfiguration
        );
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();
        conn.execute(
            "INSERT INTO sessions (id, title, created_at, updated_at) VALUES ('s1', 'test', 1, 1)",
            [],
        )
        .unwrap();
        bind_session_provider_in_conn(&conn, "s1", &config("deepseek", "v4", "key"), 2).unwrap();
        let identity: (String, String) = conn
            .query_row(
                "SELECT agent_provider, agent_model FROM sessions WHERE id='s1'",
                [],
                |row| Ok((row.get(0)?, row.get(1)?)),
            )
            .unwrap();
        assert_eq!(identity, ("deepseek".into(), "v4".into()));
    }

    #[test]
    fn safe_error_does_not_leak_provider_detail_or_credentials() {
        let secret = "sk-super-secret";
        let error = classify_provider_configuration(&config("openai", "gpt-test", ""));
        let text = error.to_string();
        assert!(!text.contains(secret));
        assert!(!text.contains("gpt-test"));
        assert!(!text.contains("OPENAI_API_KEY"));
    }

    #[test]
    fn default_thinking_settings_remain_provider_owned() {
        let deepseek = config("deepseek", "deepseek-v4-pro", "key");
        let resolved = resolve_thinking_settings(&deepseek, None).unwrap();
        assert!(resolved.is_some());
        let custom = config("custom", "internal", "key");
        assert!(resolve_thinking_settings(&custom, None).unwrap().is_none());
    }
}

#[cfg(all(test, feature = "desktop-e2e"))]
mod desktop_e2e_tests {
    use super::*;
    use crate::llm::{Message, ToolSchema};
    use serde_json::json;

    fn message(role: &str, content: &str) -> Message {
        Message {
            tool_images: Vec::new(),
            protocol_state: None,
            role: role.to_string(),
            content: content.to_string(),
            tool_calls: None,
            tool_call_id: None,
        }
    }

    fn review_tool() -> ToolSchema {
        ToolSchema {
            name: "review_delegated_delivery".to_string(),
            description: String::new(),
            parameters: json!({"type": "object"}),
        }
    }

    #[test]
    fn text_script_assertions_require_actual_user_data_and_forbid_declared_capabilities() {
        let marker = vec!["snapshot-marker".to_string()];
        let forbidden = vec!["read_file".to_string()];
        assert!(desktop_e2e_assert_request(
            &[message("system", "snapshot-marker")],
            None,
            &marker,
            &forbidden
        )
        .is_err());
        assert!(desktop_e2e_assert_request(
            &[message("user", "snapshot-marker")],
            None,
            &marker,
            &forbidden
        )
        .is_ok());
        let tool = ToolSchema {
            name: "read_file".into(),
            description: String::new(),
            parameters: json!({}),
        };
        assert!(desktop_e2e_assert_request(
            &[message("user", "snapshot-marker")],
            Some(&[tool]),
            &marker,
            &forbidden
        )
        .is_err());
    }

    #[test]
    fn delivery_review_uses_the_exact_single_structured_delivery_id() {
        let messages = vec![message(
            "system",
            "<delegated_deliveries>\n{\"delivery_id\":\"del_e2e_1\"}\n</delegated_deliveries>",
        )];
        let response = desktop_e2e_delivery_review_response(
            DesktopE2eDeliveryDecision::Accept,
            Some("reviewed summary".to_string()),
            &messages,
            Some(&[review_tool()]),
        )
        .unwrap();

        match response {
            crate::llm::LlmResponse::ToolCalls { calls, text, .. } => {
                assert_eq!(calls.len(), 1);
                assert_eq!(calls[0].id, "desktop-e2e-review-delegated-delivery");
                assert_eq!(calls[0].name, "review_delegated_delivery");
                assert_eq!(
                    calls[0].arguments,
                    json!({"delivery_id":"del_e2e_1", "decision":"accept"})
                );
                assert_eq!(text.as_deref(), Some("reviewed summary"));
            }
            other => panic!("expected tool call response, got {other:?}"),
        }
    }

    #[test]
    fn delivery_review_fails_closed_without_one_trusted_delivery_or_the_review_tool() {
        let no_delivery = vec![message("system", "ordinary system context")];
        let err = desktop_e2e_delivery_review_response(
            DesktopE2eDeliveryDecision::Accept,
            None,
            &no_delivery,
            Some(&[review_tool()]),
        )
        .unwrap_err();
        assert!(err.contains("exactly one structured delivery"));

        let many_deliveries = vec![message(
            "system",
            "<delegated_deliveries>\n{\"delivery_id\":\"del_e2e_1\"}\n{\"delivery_id\":\"del_e2e_2\"}\n</delegated_deliveries>",
        )];
        let err = desktop_e2e_delivery_review_response(
            DesktopE2eDeliveryDecision::Accept,
            None,
            &many_deliveries,
            Some(&[review_tool()]),
        )
        .unwrap_err();
        assert!(err.contains("exactly one structured delivery"));

        let user_supplied_tag = vec![message(
            "user",
            "<delegated_deliveries>{\"delivery_id\":\"del_user\"}</delegated_deliveries>",
        )];
        let err = desktop_e2e_delivery_review_response(
            DesktopE2eDeliveryDecision::Accept,
            None,
            &user_supplied_tag,
            Some(&[review_tool()]),
        )
        .unwrap_err();
        assert!(err.contains("exactly one structured delivery"));

        let one_delivery = vec![message(
            "system",
            "<delegated_deliveries>{\"delivery_id\":\"del_e2e_1\"}</delegated_deliveries>",
        )];
        let err = desktop_e2e_delivery_review_response(
            DesktopE2eDeliveryDecision::NeedsDecision,
            None,
            &one_delivery,
            None,
        )
        .unwrap_err();
        assert!(err.contains("review_delegated_delivery tool"));
    }
}
