//! Plan-and-Execute module for structured multi-step task decomposition.
//!
//! Issue #059: Plan-and-Execute dual-layer reasoning
//!
//! Architecture:
//! - `TaskComplexity` — classifies tasks by estimated step count
//! - `PlanStep` / `ExecutionPlan` — structured plan representation
//! - `PlanMode` — execution strategy selection (DirectReAct, Planned, ToT)
//! - `ComplexityEstimator` — lightweight rule-based + optional LLM complexity detection
//! - `Planner` — generates structured plans via a JSON-returning LLM call
//! - `Executor` — executes plans, validates outcomes, triggers replan on mismatch

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use crate::agent::tool::{ToolCall, ToolResult};
use crate::llm::{LlmProvider, LlmResponse, Message};

/// Task complexity classification based on estimated step count.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskComplexity {
    /// Fewer than 5 steps — use DirectReAct, no planning overhead.
    Simple,
    /// 5–10 steps — use Planned mode with structured plan.
    Moderate,
    /// 10+ steps — use Planned or TreeOfThoughts for reliable decomposition.
    Complex,
}

impl TaskComplexity {
    /// Returns the recommended plan mode for this complexity level.
    pub fn recommended_mode(&self) -> PlanMode {
        match self {
            TaskComplexity::Simple => PlanMode::DirectReAct,
            TaskComplexity::Moderate => PlanMode::Planned,
            TaskComplexity::Complex => PlanMode::Planned,
        }
    }
}

/// Execution strategy selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanMode {
    /// No planning — feed directly to agent runner (ReAct loop).
    DirectReAct,
    /// Generate a structured plan before execution.
    Planned,
    /// Tree-of-Thoughts: explore multiple plan branches (reserved for future).
    #[serde(rename = "tree_of_thoughts")]
    TreeOfThoughts,
}

impl Default for PlanMode {
    fn default() -> Self {
        PlanMode::DirectReAct
    }
}

/// A single step in an execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    /// Unique step identifier within the plan.
    pub step_id: u32,
    /// Human-readable description of what this step does.
    pub description: String,
    /// Tool call for this step as raw JSON value (avoids ToolCall Serialize bound).
    /// `None` for init/gathering steps that don't need a tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<Value>,
    /// Expected outcome after this step succeeds — used by Executor for validation.
    pub expected_outcome: String,
    /// Step IDs this step depends on (must complete before this step runs).
    #[serde(default)]
    pub depends_on: Vec<u32>,
}

impl PlanStep {
    /// Convert the JSON action value into a ToolCall (if present).
    pub fn to_tool_call(&self) -> Option<ToolCall> {
        let v = self.action.as_ref()?;
        serde_json::from_value(v.clone()).ok()
    }
}

/// A complete execution plan generated by the Planner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// Ordered list of plan steps.
    pub steps: Vec<PlanStep>,
    /// Estimated total step count.
    pub estimated_steps: usize,
    /// Selected execution mode.
    pub execution_mode: PlanMode,
}

impl ExecutionPlan {
    /// Validates the plan's internal consistency. Currently checks that every
    /// `depends_on` entry refers to a real step id present in the same plan.
    /// Without this check, a dangling dep would silently behave like "no
    /// dependency" inside `topological_waves` (the dep id is not in the
    /// remaining set, so the step is treated as ready), letting the LLM
    /// produce plans that appear to declare ordering that the executor
    /// actually does not enforce.
    pub fn validate(&self) -> Result<(), String> {
        let known: std::collections::HashSet<u32> = self.steps.iter().map(|s| s.step_id).collect();
        for step in &self.steps {
            for dep in &step.depends_on {
                if !known.contains(dep) {
                    return Err(format!(
                        "Plan step {} references unknown dependency {}",
                        step.step_id, dep
                    ));
                }
                if dep == &step.step_id {
                    return Err(format!("Plan step {} depends on itself", step.step_id));
                }
            }
        }
        Ok(())
    }

    /// Returns steps grouped into topological waves (steps with no deps first,
    /// then steps whose deps are all in earlier waves).
    pub fn topological_waves(&self) -> Vec<Vec<&PlanStep>> {
        let mut waves: Vec<Vec<&PlanStep>> = Vec::new();
        let mut remaining: HashSet<u32> = self.steps.iter().map(|s| s.step_id).collect();
        let step_map: HashMap<u32, &PlanStep> = self.steps.iter().map(|s| (s.step_id, s)).collect();

        while !remaining.is_empty() {
            let ready: Vec<&PlanStep> = self
                .steps
                .iter()
                .filter(|s| {
                    remaining.contains(&s.step_id)
                        && s.depends_on.iter().all(|dep| !remaining.contains(dep))
                })
                .collect();

            if ready.is_empty() {
                let orphan: Vec<&PlanStep> = remaining
                    .iter()
                    .filter_map(|id| step_map.get(id).copied())
                    .collect();
                if !orphan.is_empty() {
                    waves.push(orphan);
                }
                break;
            }

            waves.push(ready.clone());
            for s in ready {
                remaining.remove(&s.step_id);
            }
        }

        waves
    }

    /// Checks whether the plan is empty or a DirectReAct passthrough.
    pub fn is_trivial(&self) -> bool {
        self.steps.is_empty()
            || (self.steps.len() == 1
                && self.steps[0].action.is_none()
                && self.execution_mode == PlanMode::DirectReAct)
    }
}

/// Result of validating a step outcome against expected_outcome.
#[derive(Debug, Clone)]
pub struct OutcomeMatch {
    pub step_id: u32,
    pub matched: bool,
    pub actual: String,
    pub deviation: Option<String>,
}

/// Estimates task complexity from a user message and conversation history.
pub struct ComplexityEstimator {
    moderate_threshold: usize,
    complex_threshold: usize,
    llm_provider: Option<Box<dyn LlmProvider>>,
}

impl ComplexityEstimator {
    pub fn new() -> Self {
        Self {
            moderate_threshold: 5,
            complex_threshold: 10,
            llm_provider: None,
        }
    }

    pub fn with_provider(mut self, provider: Box<dyn LlmProvider>) -> Self {
        self.llm_provider = Some(provider);
        self
    }

    /// Estimates complexity via optional LLM call, falling back to rules.
    pub async fn estimate_complexity(
        &self,
        user_message: &str,
        history: &[(String, String)],
    ) -> TaskComplexity {
        if let Some(ref provider) = self.llm_provider {
            if let Some(c) = self
                .llm_estimate(provider.as_ref(), user_message, history)
                .await
            {
                return c;
            }
        }
        self.rule_based_estimate(user_message, history)
    }

    async fn llm_estimate(
        &self,
        provider: &dyn LlmProvider,
        user_message: &str,
        history: &[(String, String)],
    ) -> Option<TaskComplexity> {
        let history_text = if history.is_empty() {
            String::new()
        } else {
            history
                .iter()
                .take(4)
                .map(|(r, c)| format!("{}: {}", r, c))
                .collect::<Vec<_>>()
                .join("\n")
        };

        let prompt = format!(
            "你是任务复杂度估算器。分析以下用户消息，估计完成任务需要多少个独立的工具调用步骤。\
            只返回一个 JSON 对象：{{\"estimated_steps\": <数字>, \"complexity\": \"simple|moderate|complex\"}}\
            - simple: 1-4步\n- moderate: 5-10步\n- complex: 10步以上\n\n用户消息: {}\n\n历史: {}",
            user_message, history_text
        );

        let messages = vec![Message {
            tool_images: Vec::new(),
            protocol_state: None,
            role: "user".to_string(),
            content: prompt,
            tool_calls: None,
            tool_call_id: None,
        }];

        let response = provider.chat(&messages, None, None).await.ok()?;
        let LlmResponse::Text { text, .. } = response.into_parts().0 else {
            return None;
        };

        let json_str = text
            .trim()
            .trim_start_matches("```json")
            .trim_start_matches("```")
            .trim_end_matches("```")
            .trim();

        let parsed = serde_json::from_str::<serde_json::Value>(json_str).ok()?;
        let steps = parsed.get("estimated_steps")?.as_u64()? as usize;
        Some(Self::steps_to_complexity(steps))
    }

    fn rule_based_estimate(
        &self,
        user_message: &str,
        history: &[(String, String)],
    ) -> TaskComplexity {
        let msg_lower = user_message.to_lowercase();

        let multi_step_signals = [
            "和",
            "然后",
            "接着",
            "接下来",
            "首先",
            "其次",
            "另外",
            "除此之外",
            "以及",
            "also",
            "then",
            "next",
            "and then",
            "after that",
            "first",
            "finally",
            "create",
            "read",
            "update",
            "delete",
            "write",
            "multiple",
            "several",
            "all of",
        ];

        let signal_count = multi_step_signals
            .iter()
            .filter(|s| msg_lower.contains(&(*s).to_lowercase()))
            .count();

        let numbered_count = count_numbered_items(&msg_lower);
        let sentence_count = msg_lower.matches(['.', '。', '!', '？']).count();
        let history_factor = history.len().min(5);

        let estimated_steps =
            signal_count + numbered_count * 2 + (sentence_count / 3).min(5) + history_factor;

        Self::steps_to_complexity(estimated_steps)
    }

    fn steps_to_complexity(steps: usize) -> TaskComplexity {
        if steps >= 10 {
            TaskComplexity::Complex
        } else if steps >= 5 {
            TaskComplexity::Moderate
        } else {
            TaskComplexity::Simple
        }
    }
}

impl Default for ComplexityEstimator {
    fn default() -> Self {
        Self::new()
    }
}

fn count_numbered_items(text: &str) -> usize {
    let mut count = 0;
    let bytes = text.as_bytes();
    for i in 0..bytes.len().saturating_sub(3) {
        if bytes[i].is_ascii_digit()
            && i + 1 < bytes.len()
            && bytes[i + 1] == b'.'
            && i + 2 < bytes.len()
            && !bytes[i + 2].is_ascii_whitespace()
        {
            count += 1;
        }
    }
    count
}

/// Generates structured execution plans from user messages.
pub struct Planner {
    provider: Box<dyn LlmProvider>,
    max_replans: usize,
}

impl Planner {
    pub fn new(provider: Box<dyn LlmProvider>) -> Self {
        Self {
            provider,
            max_replans: 2,
        }
    }

    /// Generates an execution plan for the given task.
    pub async fn plan(
        &self,
        user_message: &str,
        history: &[(String, String)],
    ) -> Result<ExecutionPlan, String> {
        let system_prompt = Self::planner_system_prompt();
        let user_content = Self::build_user_content(user_message, history);

        let messages = vec![
            Message {
                tool_images: Vec::new(),
                protocol_state: None,
                role: "system".to_string(),
                content: system_prompt,
                tool_calls: None,
                tool_call_id: None,
            },
            Message {
                tool_images: Vec::new(),
                protocol_state: None,
                role: "user".to_string(),
                content: user_content,
                tool_calls: None,
                tool_call_id: None,
            },
        ];

        let response = self
            .provider
            .chat(&messages, None, None)
            .await
            .map_err(|e| format!("Planner LLM call failed: {}", e))?;

        match response.into_parts().0 {
            LlmResponse::Text { text, .. } => Self::parse_plan_response(&text),
            LlmResponse::ProtocolViolation { reason, .. } => Err(format!(
                "Planner received invalid tool-call protocol: {reason}"
            )),
            LlmResponse::ToolCalls { .. } => {
                Err("Planner received unexpected tool call from LLM".to_string())
            }
            LlmResponse::WithProtocol { .. } => unreachable!("flattened protocol response"),
        }
    }

    fn planner_system_prompt() -> String {
        r#"你是任务规划专家。你需要分析用户的请求，将其分解为结构化的执行计划。

## 输出格式
请严格返回以下 JSON 格式（不接受任何其他内容）：

{
  "steps": [
    {
      "step_id": 0,
      "description": "步骤的人类可读描述",
      "action": {
        "name": "tool_name",
        "arguments": {"param": "value"}
      },
      "expected_outcome": "执行成功后预期的结果描述",
      "depends_on": []
    }
  ],
  "estimated_steps": <总步骤数>,
  "execution_mode": "planned"
}

## 规则
1. step_id 必须是 0 开始的连续整数。
2. depends_on 数组包含此步骤依赖的前置 step_id（必须为空数组如果无依赖）。
3. action 是可选的：如果步骤不需要工具调用（如信息收集、初始化），设为 null。
4. estimated_steps 是总步骤数的估计值。
5. execution_mode 必须是 "planned"（复杂任务）或 "direct_react"（简单任务直接执行）。
6. 请只返回 JSON，不要有任何解释、前缀或 markdown 代码块。
7. 预期结果描述应该具体、可验证，便于后续执行器验证步骤是否成功。

## 工具命名规范
- 文件读取: read_file，参数: {"path": "文件路径"}
- 创建目录: create_directory，参数: {"path": "相对路径"}
- 文件写入: write_file，参数: {"path": "路径", "content": "内容"}
- 项目命令: run_project_command，参数: {"command": "npm/cargo 等受支持命令", "args": ["参数"]}
- 搜索: search，参数: {"query": "搜索词"}
- 其他: 使用实际工具名称

请分析用户请求并生成计划："#
            .to_string()
    }

    fn build_user_content(user_message: &str, history: &[(String, String)]) -> String {
        let mut content = format!("用户请求: {}\n\n", user_message);
        if !history.is_empty() {
            content.push_str("对话历史 (最近的优先):\n");
            for (i, (role, msg)) in history.iter().take(8).enumerate() {
                let role_label = if role == "assistant" {
                    "助手"
                } else {
                    "用户"
                };
                content.push_str(&format!("{}. {}: {}\n", i + 1, role_label, msg));
            }
            content.push('\n');
        }
        content.push_str("请根据以上信息生成执行计划。");
        content
    }

    fn parse_plan_response(response: &str) -> Result<ExecutionPlan, String> {
        let json_str = response
            .trim()
            .trim_start_matches("```json")
            .trim_start_matches("```")
            .trim_start_matches("json")
            .trim_end_matches("```")
            .trim();

        let mut parsed: ExecutionPlan = serde_json::from_str(json_str)
            .map_err(|e| format!("Failed to parse plan JSON: {}", e))?;

        let mode_str = serde_json::to_value(&parsed.execution_mode)
            .ok()
            .and_then(|v| v.as_str().map(|s| s.to_string()))
            .unwrap_or_else(|| "planned".to_string());
        parsed.execution_mode = match mode_str.to_lowercase().as_str() {
            "planned" => PlanMode::Planned,
            "direct_react" => PlanMode::DirectReAct,
            "tree_of_thoughts" | "treeofthoughts" => PlanMode::TreeOfThoughts,
            _ => PlanMode::Planned,
        };

        parsed.validate()?;
        Ok(parsed)
    }
}

/// Trait for executing tool calls — allows integration with AgentRunner
/// without creating a circular dependency.
pub trait ToolExecutor: Send + Sync {
    fn execute(&self, call: &ToolCall) -> ToolResult;
}

impl<F> ToolExecutor for F
where
    F: Fn(&ToolCall) -> ToolResult + Send + Sync,
{
    fn execute(&self, call: &ToolCall) -> ToolResult {
        (self)(call)
    }
}

/// Simple in-memory tool executor for standalone testing.
pub struct InMemoryExecutor {
    tools: HashMap<String, Box<dyn Fn(&ToolCall) -> ToolResult + Send + Sync>>,
}

impl InMemoryExecutor {
    pub fn new() -> Self {
        Self {
            tools: HashMap::new(),
        }
    }

    pub fn register(
        mut self,
        name: &str,
        handler: impl Fn(&ToolCall) -> ToolResult + 'static + Send + Sync,
    ) -> Self {
        self.tools.insert(name.to_string(), Box::new(handler));
        self
    }
}

impl ToolExecutor for InMemoryExecutor {
    fn execute(&self, call: &ToolCall) -> ToolResult {
        self.tools
            .get(&call.name)
            .map(|handler| handler(call))
            .unwrap_or_else(|| {
                ToolResult::error(&call.name, format!("Unknown tool: {}", call.name))
            })
    }
}

impl Default for InMemoryExecutor {
    fn default() -> Self {
        Self::new()
    }
}

/// Result of executing an ExecutionPlan.
#[derive(Debug)]
pub struct ExecutorResult {
    pub response: String,
    pub success: bool,
    pub replans: usize,
    pub error: Option<String>,
    pub step_outcomes: HashMap<u32, OutcomeMatch>,
}

/// Executes an ExecutionPlan, validates outcomes, and triggers replan on mismatch.
pub struct Executor {
    planner: Arc<Planner>,
    tool_registry: Arc<dyn ToolExecutor>,
    max_replans: usize,
}

impl Executor {
    pub fn new(planner: Arc<Planner>, tool_executor: Arc<dyn ToolExecutor>) -> Self {
        Self {
            planner,
            tool_registry: tool_executor,
            max_replans: 2,
        }
    }

    /// Execute a single tool call and return the result (used by ToT integration).
    pub async fn execute_tool(&self, call: &ToolCall) -> ToolResult {
        self.tool_registry.execute(call)
    }

    /// Executes the plan, checking actual outcomes against expected_outcome.
    /// If any step's outcome doesn't match, triggers replan (up to max_replans).
    pub async fn execute(&self, plan: &ExecutionPlan) -> ExecutorResult {
        let mut replan_count = 0;
        let mut current_plan = plan.clone();
        let mut step_outcomes: HashMap<u32, OutcomeMatch> = HashMap::new();
        let mut last_error_msg: Option<String> = None;

        loop {
            let wave_result = self.execute_waves(&current_plan, &mut step_outcomes).await;

            if wave_result.success {
                return ExecutorResult {
                    response: wave_result.response,
                    success: true,
                    replans: replan_count,
                    error: None,
                    step_outcomes,
                };
            }

            last_error_msg = Some(wave_result.response.clone());

            if replan_count >= self.max_replans {
                break;
            }

            replan_count += 1;

            let failure_summary = format!(
                "Previous plan failed. Summary: {}\nFailed plan had {} steps.\nPlease generate an improved plan:",
                wave_result.response,
                current_plan.steps.len()
            );

            match self.trigger_replan(&failure_summary).await {
                Ok(new_plan) => current_plan = new_plan,
                Err(e) => {
                    return ExecutorResult {
                        response: e.clone(),
                        success: false,
                        replans: replan_count,
                        error: Some(e),
                        step_outcomes,
                    };
                }
            }
        }

        let final_error_msg =
            last_error_msg.unwrap_or_else(|| "Plan execution failed after max replans".to_string());
        ExecutorResult {
            response: final_error_msg.clone(),
            success: false,
            replans: replan_count,
            error: Some(final_error_msg),
            step_outcomes,
        }
    }

    /// Executes all steps in topological waves.
    async fn execute_waves(
        &self,
        plan: &ExecutionPlan,
        step_outcomes: &mut HashMap<u32, OutcomeMatch>,
    ) -> WaveExecutionResult {
        let mut results: HashMap<u32, ToolResult> = HashMap::new();
        let mut all_success = true;
        let mut response_parts: Vec<String> = Vec::new();

        for wave in plan.topological_waves() {
            let wave_results = self.execute_parallel_wave(wave, &results).await;

            for (step_id, result) in wave_results {
                results.insert(step_id, result.clone());
                if !result.success {
                    all_success = false;
                }
                // Validate outcome
                let step = plan.steps.iter().find(|s| s.step_id == step_id);
                if let Some(s) = step {
                    let outcome = validate_outcome(s, &result);
                    step_outcomes.insert(step_id, outcome);
                    response_parts.push(format!(
                        "[Step {}] {}: {}",
                        step_id,
                        if result.success { "OK" } else { "FAILED" },
                        result.content
                    ));
                }
            }
        }

        let response = if response_parts.is_empty() {
            "Plan executed with no tool steps.".to_string()
        } else {
            response_parts.join("\n")
        };

        WaveExecutionResult {
            response,
            success: all_success,
        }
    }

    /// Executes a single wave of steps.
    async fn execute_parallel_wave(
        &self,
        steps: Vec<&PlanStep>,
        _prior_results: &HashMap<u32, ToolResult>,
    ) -> Vec<(u32, ToolResult)> {
        let mut results: Vec<(u32, ToolResult)> = Vec::new();

        // Separate steps with and without tool calls.
        let (mut tool_steps, info_steps): (Vec<&PlanStep>, Vec<&PlanStep>) =
            steps.into_iter().partition(|s| s.action.is_some());

        // Info steps (no tool call needed).
        for step in info_steps {
            results.push((
                step.step_id,
                ToolResult::success(
                    &format!("step_{}", step.step_id),
                    format!("[Info] {}", step.description),
                ),
            ));
        }

        // Tool steps.
        let parallel_steps: Vec<PlanStep> = tool_steps
            .iter()
            .filter(|s| s.depends_on.is_empty())
            .map(|s| (**s).clone())
            .collect();

        let sequential_steps: Vec<PlanStep> = tool_steps
            .iter()
            .filter(|s| !s.depends_on.is_empty())
            .map(|s| (**s).clone())
            .collect();

        // Parallel for independent steps.
        if !parallel_steps.is_empty() {
            let parallel_results = self.execute_tools_parallel(parallel_steps).await;
            results.extend(parallel_results);
        }

        // Sequential for steps with dependencies.
        for step in sequential_steps {
            if let Some(action) = step.to_tool_call() {
                let result = self.tool_registry.execute(&action);
                results.push((step.step_id, result));
            }
        }

        results
    }

    /// Executes multiple tool calls concurrently via tokio::spawn.
    async fn execute_tools_parallel(&self, steps: Vec<PlanStep>) -> Vec<(u32, ToolResult)> {
        let registry = self.tool_registry.clone();

        let handles: Vec<_> = steps
            .into_iter()
            .filter_map(|step| {
                let action = step.to_tool_call()?;
                let step_id = step.step_id;
                let registry = registry.clone();
                Some(tokio::spawn(async move {
                    let result = registry.execute(&action);
                    (step_id, result)
                }))
            })
            .collect();

        let mut results = Vec::new();
        for handle in handles {
            if let Ok(result) = handle.await {
                results.push(result);
            }
        }

        results
    }

    /// Triggers replan by calling the Planner with failure context.
    async fn trigger_replan(&self, failure_summary: &str) -> Result<ExecutionPlan, String> {
        let messages = vec![Message {
            tool_images: Vec::new(),
            protocol_state: None,
            role: "user".to_string(),
            content: failure_summary.to_string(),
            tool_calls: None,
            tool_call_id: None,
        }];

        let response = self
            .planner
            .provider
            .chat(&messages, None, None)
            .await
            .map_err(|e| format!("Replan LLM call failed: {}", e))?;

        match response.into_parts().0 {
            LlmResponse::Text { text, .. } => Planner::parse_plan_response(&text)
                .map_err(|e| format!("Failed to parse replan: {}", e)),
            LlmResponse::ProtocolViolation { reason, .. } => Err(format!(
                "Planner received invalid tool-call protocol: {reason}"
            )),
            LlmResponse::ToolCalls { .. } => {
                Err("Planner received unexpected tool call during replan".to_string())
            }
            LlmResponse::WithProtocol { .. } => unreachable!("flattened protocol response"),
        }
    }
}

/// Intermediate result from executing a wave of steps.
struct WaveExecutionResult {
    response: String,
    success: bool,
}

/// Checks whether an actual tool result matches the expected outcome for a step.
pub fn validate_outcome(step: &PlanStep, result: &ToolResult) -> OutcomeMatch {
    let actual = result.content.to_lowercase();
    let expected = step.expected_outcome.to_lowercase();

    let expected_keywords: Vec<&str> = expected
        .split_whitespace()
        .filter(|w| w.len() > 3)
        .collect();

    let matched_keywords = expected_keywords
        .iter()
        .filter(|kw| actual.contains(*kw))
        .count();

    let match_ratio = if expected_keywords.is_empty() {
        1.0
    } else {
        matched_keywords as f64 / expected_keywords.len() as f64
    };

    let matched = result.success && match_ratio >= 0.5;

    OutcomeMatch {
        step_id: step.step_id,
        matched,
        actual: result.content.clone(),
        deviation: if matched {
            None
        } else {
            Some(format!(
                "Expected keywords {:?}, matched {:.0}%",
                expected_keywords,
                match_ratio * 100.0
            ))
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plan_step_to_tool_call() {
        let step = PlanStep {
            step_id: 0,
            description: "Read file".to_string(),
            action: Some(serde_json::json!({
                "name": "read_file",
                "arguments": {"path": "test.txt"},
                "id": "call-1"
            })),
            expected_outcome: "file contents".to_string(),
            depends_on: vec![],
        };
        let tc = step.to_tool_call();
        assert!(tc.is_some());
        let tc = tc.unwrap();
        assert_eq!(tc.name, "read_file");
    }

    #[test]
    fn test_topological_waves_simple() {
        let plan = ExecutionPlan {
            steps: vec![
                PlanStep {
                    step_id: 0,
                    description: "A".into(),
                    action: None,
                    expected_outcome: "".into(),
                    depends_on: vec![],
                },
                PlanStep {
                    step_id: 1,
                    description: "B".into(),
                    action: None,
                    expected_outcome: "".into(),
                    depends_on: vec![0],
                },
                PlanStep {
                    step_id: 2,
                    description: "C".into(),
                    action: None,
                    expected_outcome: "".into(),
                    depends_on: vec![0],
                },
            ],
            estimated_steps: 3,
            execution_mode: PlanMode::Planned,
        };
        let waves = plan.topological_waves();
        assert_eq!(waves.len(), 2); // wave1: [step0], wave2: [step1, step2]
        assert_eq!(waves[0].len(), 1);
        assert_eq!(waves[1].len(), 2);
    }

    #[test]
    fn test_complexity_estimator_rule_based() {
        let est = ComplexityEstimator::new();
        // Empty/simple message → Simple
        let simple = est.rule_based_estimate("Hello", &[]);
        assert_eq!(simple, TaskComplexity::Simple);

        // Algorithm must not panic and must return a valid enum variant
        let result = est.rule_based_estimate("test message", &[]);
        assert!(
            matches!(
                result,
                TaskComplexity::Simple | TaskComplexity::Moderate | TaskComplexity::Complex
            ),
            "Expected valid complexity, got {:?}",
            result
        );
    }

    #[test]
    fn test_validate_outcome_match() {
        let step = PlanStep {
            step_id: 0,
            description: "Read file".into(),
            action: None,
            expected_outcome: "file contents returned successfully".into(),
            depends_on: vec![],
        };
        let result = ToolResult::success(
            "read_file",
            "Here are the file contents returned successfully",
        );
        let outcome = validate_outcome(&step, &result);
        assert!(outcome.matched);
    }

    #[test]
    fn test_validate_outcome_no_match() {
        let step = PlanStep {
            step_id: 0,
            description: "Read file".into(),
            action: None,
            expected_outcome: "file contents displayed".into(),
            depends_on: vec![],
        };
        let result = ToolResult::success("read_file", "Error: permission denied");
        let outcome = validate_outcome(&step, &result);
        assert!(!outcome.matched);
    }

    #[test]
    fn test_validate_plan_accepts_well_formed_deps() {
        let plan = ExecutionPlan {
            steps: vec![
                PlanStep {
                    step_id: 0,
                    description: "A".into(),
                    action: None,
                    expected_outcome: "".into(),
                    depends_on: vec![],
                },
                PlanStep {
                    step_id: 1,
                    description: "B".into(),
                    action: None,
                    expected_outcome: "".into(),
                    depends_on: vec![0],
                },
            ],
            estimated_steps: 2,
            execution_mode: PlanMode::Planned,
        };
        assert!(plan.validate().is_ok());
    }

    #[test]
    fn test_validate_plan_rejects_dangling_dep() {
        let plan = ExecutionPlan {
            steps: vec![PlanStep {
                step_id: 0,
                description: "A".into(),
                action: None,
                expected_outcome: "".into(),
                depends_on: vec![99],
            }],
            estimated_steps: 1,
            execution_mode: PlanMode::Planned,
        };
        let err = plan.validate().unwrap_err();
        assert!(err.contains("unknown dependency"), "got: {}", err);
    }

    #[test]
    fn test_validate_plan_rejects_self_dep() {
        let plan = ExecutionPlan {
            steps: vec![PlanStep {
                step_id: 0,
                description: "A".into(),
                action: None,
                expected_outcome: "".into(),
                depends_on: vec![0],
            }],
            estimated_steps: 1,
            execution_mode: PlanMode::Planned,
        };
        let err = plan.validate().unwrap_err();
        assert!(err.contains("depends on itself"), "got: {}", err);
    }
}
